[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q3 = "2aHq1dg44vmdxxBuzPqw2jZTGMtvex12Kt3dqmHqe93U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
