[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_nft_staking = "DhmZNmbCM8G4hBB3gaXAKy6FokqSPygYe3UicYxyZG9Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mohibrahim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
