[toolchain]
anchor_version = "0.29.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault_q3 = "79p2LqH7nZagKSmPZGGrVgBRh78mMKPn9PA4aKcRrbqg"

[programs.devnet]
anchor_vault_q3 = "5bNj7dPZ9a2y2us2QJBkDmXmhtxkgGhSZ5itrTAUwatE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 15000